### ISSUE TITLE
Calculate wrong cancel fee for SELL order.

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/victionchain#196]
I tested cancel order with TOMO/USDT and ETH/TOMO.

Steps:
- Pair TOMO/USDT, Available balance 1000 TOMO 
- SELL 1000 TOMO
- Cancel order (0% filled)
- Fee 1 TOMO, Available balance 999 
-> Expect, Fee 0.1 TOMO, Available balance 999.9

Steps:
- Pair ETH/TOMO, Available balance 1 ETH
- SELL 1 ETH
- Cancel order (0% filled)
- Fee 0.001 ETH, Available balance 0.999
-> Expect, Fee 0.0001 ETH, Available balance 0.9999

It is OK when I test with BUY order

**Comment by thanhnguyennguyen** [comment]
Missing update **TomoXBaseCancelFee** in this PR https://github.com/tomochain/tomochain/pull/31/files may cause the issue.
It should happen for both BUY/SELL orders. 
But you said `It is OK when I test with BUY order`. It's so weird 🤔

**Comment by thanhson1085** [comment]
That pull request chain fee decimal, it think it does not relate to this issue.
