### ISSUE TITLE
Missing collateralToken + lendToken validation

### ISSUE THREAD

**Issue by thanhnguyennguyen** [BuildOnViction/victionchain#241]
We don't have any validation to verify whether the collateral token of `borrow item` exists in the collateral list of lendToken 

For `BORROW` object:
- [x] Collateral belong to collateralList of lendToken (defined in contract)
- [x] CollateralToken != LendToken
- [x] Validate collateralToken of TOPUP object

For `INVEST` object:
- [x] ~~Validate if lendToken belong to lendToken list of the relayer (defined in contract)~~ (**_done in `ValidPair`_**)

**Comment by thanhson1085** [comment]
We also should NOT allow others that have lendingToken = collateralToken
Need to validate both pool and core
