### ISSUE TITLE
Upgrade TomoChain's EVM to support the latest solidity compiler version

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/victionchain#289]

**Comment by nyeates** [comment]
Community is curious on the extent of this item. What is involved? Scope? How long it will take?
We are hoping it can help with giving quick access to a LuaSwap interface on the Tomochain network.

**Comment by thanhson1085** [comment]
Plan to have the public Testnet in Oct.
It supports Solc 0.6+ (current Solc <0.5)
