### ISSUE TITLE
Can't get block validator ??

### ISSUE THREAD

**Issue by sieubanana** [BuildOnViction/victionchain#291]
I set up a pritvatr testnet with 3 masternodes and epoch set to 18.
When the epoch completes (i.e., 18 blocks are created), the nodes cannot move forward. They return the following error:

INFO [06-18|04:55:55] Committing new block                     number=18 txs=1 special-txs=1 uncles=0 elapsed=6.554ms
WARN [06-18|04:55:55] Block sealing failed                     err="can't get block validator: This block is not checkpoint block epoc."

It looks like the nodes cannot establish themselves as masternodes for the new epoch.
Could you please advise.

**Comment by thanhnguyennguyen** [comment]
Hi @sieubanana , 
If you set epoch = 18 in your genesis file, please update this value to 18 as well, 
https://github.com/tomochain/tomochain/blob/8ba9ad4ea3c9944d5387fd0f4d16d64bbeffeaa5/common/constants.go#L16
```
        EpocBlockSecret        = 14
	EpocBlockOpening       = 16
	EpocBlockRandomize     = 18
```
then rebuild

**Comment by thanhnguyennguyen** [comment]
I strongly recommend you set epoch > 100 (180 is good)
