### ISSUE TITLE
Data crashed ???

### ISSUE THREAD

**Issue by sieubanana** [BuildOnViction/victionchain#292]
Hello, Im using 3 private nodes,
but the 3 servers get restared unexpectedly
then i cannot start 3 nodes again

the console is 
INFO [06-18|10:55:44] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-18|11:55:44] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-18|12:55:44] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-18|13:55:44] Regenerated local transaction journal    transactions=0 accounts=0
INFO [06-18|14:55:44] Regenerated local transaction journal    transactions=0 accounts=0

The database got crashed and could not recovered to continue ???
Can you advise please?

thank you

**Comment by thanhnguyennguyen** [comment]
Hi @sieubanana , 
Please provide more logs 
If you see any `ERROR` log, please show here
