### ISSUE TITLE
Cancellation fee update

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/victionchain#305]
Current: cancellation fee = 1/10 trading fee
Update to flat fee: 0.0001 TOMO

**Comment by thanhnguyennguyen** [comment]
It requires all tokens pairing with TOMO (token / TOMO or TOMO / token)
This case: 
https://dex.tomochain.com/trade/YFI-USDT
**have YFI / USDT, not have YFI / TOMO (or TOMO / YFI ) may cause unexpected error**
