### ISSUE TITLE
CRTS Price update on TomoWallet

### ISSUE THREAD

**Issue by Cryptotipsfr** [BuildOnViction/victionchain#316]
Can you show usd value of CRTS on tomowallet ? the token is already listed on visiodex.com
I would also like to know the listing conditions for tomodex.
And when will the tomodex that looks like uniswap be available?

Thank's !

**Comment by thanhnguyennguyen** [comment]
Hi @Cryptotipsfr 
- for `price display in TomoWallet`, please open issue in https://github.com/tomochain/tomowallet
- for TomoDEX listing, please request in TomoDEX telegram channel: https://web.telegram.org/#/im?p=@TomoDEX_Official

Thanks,
Nguyen
