### ISSUE TITLE
Transaction failed but token fee got deducted

### ISSUE THREAD

**Issue by KrishnaDeqode** [BuildOnViction/victionchain#324]
https://scan.tomochain.com/txs/0xcaca6f613b77c43e4ddda27d55c9fb36c55614c2055ee01699ee401e175bcc5f
https://scan.tomochain.com/txs/0xfc9e2648cbf4aa26c1df814f04c5e362064081064438af0c49654dd301fc0152

Both of my above transactions failed, Although same code worked on testnet.
I would like to know the reason why they failed as well, Also if they failed then why 10 IDRP (each txn) got deducted from my balance.

**Comment by thanhson1085** [comment]
You need to pay fee for your tx (both failed or success).

I think that you need to check the contract code and your setup to know the reason they failed.

**Comment by KrishnaDeqode** [comment]
I am facing a weird situation here. Let me explain
If I transfer some tokens to a random address from my setup -> It fails the first time
Then I transfer some token to the same address from tomochain issuer UI (from the contract issuer account) -> It works fine
Then I again transfer some tokens to the same address from  my setup -> This time it works

So basically, It doesn't work from my setup for a fresh random address that doesn't have any transaction history at all (basically 0 balance).
Once you do a transaction on that address from the issuer account OR let's say it already has that token from some past transactions, In that case, the transaction from my setup works fine.

Do we have any whitelist or something mechanism in Tomo?

**Comment by KrishnaDeqode** [comment]
Re Contract Code: I haven't done any changes to that, Using the standard TRC-21 contract with Tomo-Z Protocol.

**Comment by KrishnaDeqode** [comment]
New Update: This is only happening from my system, First txn to any new account is not working if done via my setup.
It's working if done via Tomo UI OR Metamask as well, After that from 2nd txn onwards, all work fine via my setup as well.
Also, this is only happening when there is a transaction fee in the TRC-21 contract,  With 0 fee it's working fine.

**Comment by thanhson1085** [comment]
I think you need to check the gas limit for the tx.

**Comment by KrishnaDeqode** [comment]
Ok, I will try. Thanks

**Comment by KrishnaDeqode** [comment]
You are right, My gas calculations were wrong. I was always getting gasLimit in the range of 46K while it was using 70-72K.
What is the best/correct way to calculate gasLimit for tomoChain? Or maybe I should set a multiplier.

**Comment by KrishnaDeqode** [comment]
Thanks for the help @thanhson1085 . Closing this issue now.

**Comment by vagucs** [comment]
There is something serious, if I send a token in the amount zero, or if there is a failure, there is always the fee discount, if someone wants to deplete the funds of a token, just keep sending token 0. I think this should be rethought.

**Comment by vagucs** [comment]
See this 0x3a88e6c7b1ddc5db752e8211c4a68014b03c58d163ced14588bf129ad6b2e22c
Zero transaction on Lua contract.
