### ISSUE TITLE
tomo nodes pending transation question 

### ISSUE THREAD

**Issue by zacker0515** [BuildOnViction/victionchain#341]
hello TOMO guys:
   I start my node by  " tomo  --syncmode "full" --datadir /data/tomo --networkid 88 --port 30304   --keystore /data/tomo/keystore --password /data/tomo/pass  --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcport 8547 --rpcvhosts "*" --rpcapi "db,eth,net,web3,personal,debug,txpool"   --gcmode "archive"  --ws --wsaddr 0.0.0.0 --wsport 8548 --wsorigins "*" --unlock "address" --identity "cccc" --mine --gasprice 2500  --bootnodes "enode://fd3da177f9492a39d1e7ce036b05745512894df251399cb3ec565081cb8c6dfa1092af8fac27991e66b6af47e9cb42e02420cc89f8549de0ce513ee25ebffc3a@3.212.20.0:30303"   --ethstats coinex:getty-site-pablo-auger-room-sos-blair-shin-whiz-delhi@stats.tomochain.com:443 "  evertyting is fine  until recently I need to get pending transaction , I  use web3.py to get the pending nonce , for eg w3.eth.get_transaction_count('0xDEdC5Cf2d9CaA1e1DA0d5F0240119E86a4377984', 'pending') an error occred  
![image](https://user-images.githubusercontent.com/81207283/145358846-c38272ac-5ef2-4759-9115-0e8e07dc70ec.png)

but when I cheng the url into https://rpc.tomochain.com ,everthing is fine. Am I wrong when I start the node?

**Comment by zacker0515** [comment]
hope for your help

**Comment by thanhnguyennguyen** [comment]
@zacker0515  try to add this flag `--announce-txs`

**Comment by zacker0515** [comment]
> 



> @zacker0515 try to add this flag `--announce-txs`

that works for me , Thanks for your help ^-^
