### ISSUE TITLE
Do something if the order pool is full

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/victionchain#90]
```
if uint64(len(pool.all)) >= pool.config.GlobalSlots+pool.config.GlobalQueue {
}
```
So here, even the pool if full, you are not doing anything. You deleted the origin codes in the geth but didn't add any codes here. So attacker can send lots of order txs here to fill the pool and in this case, normal orders will be slowed down. I know "promoteExecutables" function will be called later but I do think you should add some logic here.

**Comment by thanhnguyennguyen** [comment]
fixed in https://github.com/tomochain/tomochain/pull/94/
